tree "domain" of process;
space all_domains = recursive "domain";

all_domains	ENTER	all_domains,
		READ	all_domains,
		WRITE	all_domains,
		SEE	all_domains;

function log
{
	local printk buf.message=$1 + "\n";
	update buf;
}

* getprocess * {
	enter(process, @"domain/init");
	process.med_sact = 0x3fffffff;
	return ALLOW;
}

* fork * {
	log("MEDUSA_EVENT fork");
	return ALLOW;
}

* ptrace * {
	log("MEDUSA_EVENT ptrace");
	return ALLOW;
}

function _init
{
}
