#
# file for the Linux kernel part of Medusa DS9 Security System,
# L1 - hooks
#

# for GCOV coverage profiling
ifdef CONFIG_SECURITY_MEDUSA_GCOV_PROFILE
GCOV_PROFILE := y
endif

O_TARGET := l1

export-objs :=

obj-y:= medusa.o

