tree "fs" clone of file by getfile getfile.filename;
primary tree "fs";
tree "domain" of process;
space all_domains = recursive "domain";
space all_objects = recursive "/";

all_domains	ENTER	all_domains,
		READ	all_domains, all_objects,
		WRITE	all_domains, all_objects,
		SEE	all_domains, all_objects;

function log
{
	local printk buf.message=$1 + "\n";
	update buf;
}

* getprocess * {
	enter(process, @"domain/init");
	process.med_sact = 0;
	return ALLOW;
}

* getipc * {
	ipc.med_oact = 0x3fffffff;
	ipc.vs = space all_objects;
	return ALLOW;
}

* ipc_perm * { return ALLOW; }

* ipc_msgsnd * {
	log("MEDUSA_ADAPTIVE_RECORDED_ALLOW");
	return ALLOW;
}

* ipc_msgrcv * {
	log("MEDUSA_ADAPTIVE_WITHHELD_DENY");
	return DENY;
}

* ipc_ctl * { return ALLOW; }

function _init
{
	local process init.pid = 1;

	if (fetch init) {
		enter(init, @"domain/init");
		update init;
	}
}
