tree "fs" clone of file by getfile getfile.filename;
primary tree "fs";
tree "domain" of process;

space all_domains = recursive "domain";
space all_files = recursive "/";

all_domains	ENTER	all_domains,
		READ	all_domains, all_files,
		WRITE	all_domains, all_files,
		SEE	all_domains, all_files;

function log
{
	local printk buf.message=$1 + "\n";
	update buf;
}

* getprocess * {
	enter(process, @"domain/init");
	process.med_sact = 0x3fffffff;
	return ALLOW;
}

* getfile * {
	file.med_oact = 0x3fffffff;
	file.vs = space all_files;
	return ALLOW;
}

* getipc * {
	ipc.med_oact = 0x3fffffff;
	ipc.vs = space all_files;
	return ALLOW;
}

all_domains pexec all_files {
	log("MEDUSA_EVENT pexec");
	return ALLOW;
}
all_domains fexec all_files {
	log("MEDUSA_EVENT fexec");
	return ALLOW;
}
all_domains setresuid {
	log("MEDUSA_EVENT setresuid");
	return ALLOW;
}
all_domains mkdir all_files {
	log("MEDUSA_EVENT mkdir");
	return ALLOW;
}
all_domains mknod all_files {
	log("MEDUSA_EVENT mknod");
	return ALLOW;
}
all_domains open all_files {
	log("MEDUSA_EVENT open");
	file.vs = space all_files;
	update file;
	return ALLOW;
}
all_domains chmod all_files {
	log("MEDUSA_EVENT chmod");
	return ALLOW;
}
all_domains chown all_files {
	log("MEDUSA_EVENT chown");
	return ALLOW;
}
all_domains fcntl all_files {
	log("MEDUSA_EVENT fcntl");
	return ALLOW;
}
all_domains truncate all_files {
	log("MEDUSA_EVENT truncate");
	return ALLOW;
}
all_domains symlink all_files {
	log("MEDUSA_EVENT symlink");
	return ALLOW;
}
all_domains link all_files {
	log("MEDUSA_EVENT link");
	return ALLOW;
}
all_domains rename all_files {
	log("MEDUSA_EVENT rename");
	return ALLOW;
}
all_domains unlink all_files {
	log("MEDUSA_EVENT unlink");
	return ALLOW;
}
all_domains rmdir all_files {
	log("MEDUSA_EVENT rmdir");
	return ALLOW;
}
all_domains chroot all_files {
	log("MEDUSA_EVENT chroot");
	return ALLOW;
}
* ipc_perm * { log("MEDUSA_EVENT ipc_perm"); return ALLOW; }
* ipc_ctl * { log("MEDUSA_EVENT ipc_ctl"); return ALLOW; }
* ipc_associate * { log("MEDUSA_EVENT ipc_associate"); return ALLOW; }
* ipc_semop * { log("MEDUSA_EVENT ipc_semop"); return ALLOW; }
* ipc_shmat * { log("MEDUSA_EVENT ipc_shmat"); return ALLOW; }
* ipc_msgsnd * { log("MEDUSA_EVENT ipc_msgsnd"); return ALLOW; }
* ipc_msgrcv * { log("MEDUSA_EVENT ipc_msgrcv"); return ALLOW; }

function _init
{
}
