#
# Makefile for the Linux kernel part of Medusa DS9 Security System
#

# note that the order is important here!

obj-$(CONFIG_MEDUSA_L3_TESTING) := vs_model-tests.o
obj-$(CONFIG_MEDUSA_L3_TESTING) += med_model-tests.o
obj-$(CONFIG_MEDUSA_L3_TESTING) += registry-tests.o
obj-$(CONFIG_MEDUSA_L3_TESTING) += task-context-tests.o
obj-$(CONFIG_MEDUSA_L3_TESTING) += object-context-tests.o
obj-$(CONFIG_MEDUSA_L3_TESTING) += blob-access-tests.o
obj-$(CONFIG_MEDUSA_L3_TESTING) += audit-tests.o
obj-$(CONFIG_MEDUSA_L3_TESTING) += comm-tests.o
obj-$(CONFIG_MEDUSA_L3_TESTING) += med_cache-tests.o
