tree "fs" clone of file by getfile getfile.filename;
primary tree "fs";
tree "domain" of process;

space all_domains = recursive "domain";
space all_objects = recursive "/";

all_domains	ENTER	all_domains,
		READ	all_domains, all_objects,
		WRITE	all_domains, all_objects,
		SEE	all_domains, all_objects;

* getprocess * {
	enter(process, @"domain/init");
	process.med_sact = 0x7fffffff;
	process.audit = 0;
	return ALLOW;
}

* getsocket * {
	return ALLOW;
}

* socket_create * {
	return ALLOW;
}

* socket_bind_access * {
	return ALLOW;
}

* socket_connect_access * {
	return ALLOW;
}

* socket_listen_access * {
	return ALLOW;
}

* socket_accept_access * {
	return ALLOW;
}

* socket_sendmsg_access * {
	return ALLOW;
}

* socket_recvmsg_access * {
	return ALLOW;
}

function _init
{
}
