/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef _UAPI_LINUX_MEDUSA_H
#define _UAPI_LINUX_MEDUSA_H

#include <linux/types.h>

/*
 * Medusa protocol v4
 *
 * Every fixed-width field is little endian.  A frame is one header followed
 * by payload_length bytes of TLVs.  The reserved header field and all TLV
 * padding bytes must be zero.  Unknown TLVs with MEDUSA_TLV_F_REQUIRED set
 * make the containing frame invalid; other unknown TLVs are ignored.
 */
#define MEDUSA_PROTOCOL_VERSION			4U
#define MEDUSA_FRAME_HEADER_SIZE		32U
#define MEDUSA_TLV_HEADER_SIZE			8U
#define MEDUSA_FRAME_MAX_PAYLOAD		(1024U * 1024U)
#define MEDUSA_FRAME_MAX_SIZE			\
	(MEDUSA_FRAME_HEADER_SIZE + MEDUSA_FRAME_MAX_PAYLOAD)
#define MEDUSA_TLV_ALIGN			8U
#define MEDUSA_TLV_ALIGN_UP(length)		\
	(((length) + MEDUSA_TLV_ALIGN - 1U) & ~(MEDUSA_TLV_ALIGN - 1U))

struct medusa_frame_header {
	__le16 version;
	__le16 type;
	__le32 flags;
	__le32 payload_length;
	__le32 reserved;
	__le64 request_id;
	__le64 policy_generation;
};

struct medusa_tlv {
	__le16 type;
	__le16 flags;
	__le32 length; /* header + value, excluding zero padding */
};

#define MEDUSA_FRAME_F_REQUIRED_MASK		0U
#define MEDUSA_TLV_F_REQUIRED			(1U << 0)
#define MEDUSA_TLV_F_ARRAY			(1U << 1)

enum medusa_protocol_state {
	MEDUSA_STATE_DISCONNECTED = 0,
	MEDUSA_STATE_HANDSHAKE = 1,
	MEDUSA_STATE_DEFINITIONS = 2,
	MEDUSA_STATE_POLICY_INSTALL = 3,
	MEDUSA_STATE_READY = 4,
	MEDUSA_STATE_DEGRADED = 5,
};

enum medusa_message_type {
	MEDUSA_MSG_HELLO = 1,
	MEDUSA_MSG_HELLO_ACK = 2,
	MEDUSA_MSG_CLASS_DEFINITION = 16,
	MEDUSA_MSG_EVENT_DEFINITION = 17,
	MEDUSA_MSG_DEFINITIONS_DONE = 18,
	MEDUSA_MSG_POLICY_BEGIN = 32,
	MEDUSA_MSG_POLICY_EVENT = 33,
	MEDUSA_MSG_POLICY_COMMIT = 34,
	MEDUSA_MSG_POLICY_READY = 35,
	MEDUSA_MSG_DECISION_REQUEST = 48,
	MEDUSA_MSG_DECISION_REPLY = 49,
	MEDUSA_MSG_DECISION_CANCEL = 50,
	MEDUSA_MSG_DECISION_PROGRESS = 51,
	MEDUSA_MSG_OBJECT_FETCH = 52,
	MEDUSA_MSG_OBJECT_FETCH_REPLY = 53,
	MEDUSA_MSG_OBJECT_UPDATE = 54,
	MEDUSA_MSG_OBJECT_UPDATE_REPLY = 55,
	MEDUSA_MSG_AUDIT = 56,
	MEDUSA_MSG_ERROR = 255,
};

enum medusa_tlv_type {
	MEDUSA_TLV_MIN_VERSION = 1,
	MEDUSA_TLV_MAX_VERSION = 2,
	MEDUSA_TLV_REQUIRED_FEATURES = 3,
	MEDUSA_TLV_OPTIONAL_FEATURES = 4,
	MEDUSA_TLV_ENABLED_FEATURES = 5,
	MEDUSA_TLV_STATE = 6,
	MEDUSA_TLV_CLASS_ID = 16,
	MEDUSA_TLV_EVENT_ID = 17,
	MEDUSA_TLV_NAME = 18,
	MEDUSA_TLV_OBJECT_SIZE = 19,
	MEDUSA_TLV_EVENT_SIZE = 20,
	MEDUSA_TLV_ATTRIBUTE = 21,
	MEDUSA_TLV_SUBJECT_CLASS_ID = 22,
	MEDUSA_TLV_OBJECT_CLASS_ID = 23,
	MEDUSA_TLV_SUBJECT_NAME = 24,
	MEDUSA_TLV_OBJECT_NAME = 25,
	MEDUSA_TLV_TRIGGER = 26,
	MEDUSA_TLV_ENFORCEMENT = 27,
	MEDUSA_TLV_FALLBACK_POLICY = 32,
	MEDUSA_TLV_ANSWER = 33,
	MEDUSA_TLV_EVENT_DATA = 34,
	MEDUSA_TLV_SUBJECT_DATA = 35,
	MEDUSA_TLV_OBJECT_DATA = 36,
	MEDUSA_TLV_STATUS = 37,
	MEDUSA_TLV_ERROR_CODE = 48,
	MEDUSA_TLV_ERROR_MESSAGE = 49,
	MEDUSA_TLV_OFFENDING_TYPE = 50,
};

enum medusa_feature {
	MEDUSA_FEATURE_OUT_OF_ORDER_REPLIES = 1ULL << 0,
	MEDUSA_FEATURE_DECISION_PROGRESS = 1ULL << 1,
	MEDUSA_FEATURE_OBJECT_FETCH_UPDATE = 1ULL << 2,
	MEDUSA_FEATURE_AUDIT_FRAMES = 1ULL << 3,
};

#define MEDUSA_REQUIRED_FEATURES		\
	MEDUSA_FEATURE_OUT_OF_ORDER_REPLIES
#define MEDUSA_SUPPORTED_FEATURES		\
	(MEDUSA_FEATURE_OUT_OF_ORDER_REPLIES |	\
	 MEDUSA_FEATURE_DECISION_PROGRESS |	\
	 MEDUSA_FEATURE_OBJECT_FETCH_UPDATE |	\
	 MEDUSA_FEATURE_AUDIT_FRAMES)

enum medusa_attribute_type {
	MEDUSA_ATTR_END = 0,
	MEDUSA_ATTR_UNSIGNED = 1,
	MEDUSA_ATTR_SIGNED = 2,
	MEDUSA_ATTR_STRING = 3,
	MEDUSA_ATTR_BITMAP = 4,
	MEDUSA_ATTR_BYTES = 5,
};

#define MEDUSA_ATTR_F_READ_ONLY			(1U << 0)
#define MEDUSA_ATTR_F_PRIMARY_KEY		(1U << 1)
#define MEDUSA_ATTR_F_BIG_ENDIAN		(1U << 2)
#define MEDUSA_ATTR_F_LITTLE_ENDIAN		(1U << 3)

struct medusa_attribute_definition {
	__le32 id;
	__le32 offset;
	__le32 length;
	__le16 type;
	__le16 flags;
	__le16 name_length;
	__le16 reserved;
};

enum medusa_fallback_policy {
	MEDUSA_FALLBACK_BASELINE_ALLOW = 0,
	MEDUSA_FALLBACK_BASELINE_DENY = 1,
	MEDUSA_FALLBACK_ONLINE_REQUIRED = 2,
};

enum medusa_decision_answer {
	MEDUSA_ANSWER_ERROR = -1,
	MEDUSA_ANSWER_FORCE_ALLOW = 0,
	MEDUSA_ANSWER_DENY = 1,
	MEDUSA_ANSWER_FAKE_ALLOW = 2,
	MEDUSA_ANSWER_ALLOW = 3,
};

#endif /* _UAPI_LINUX_MEDUSA_H */
