# For the Linux kernel part of Medusa DS9 Security System,
# L4/constable

# for GCOV coverage profiling
ifdef CONFIG_SECURITY_MEDUSA_GCOV_PROFILE
GCOV_PROFILE := y
endif

l4-constable-y := chardev.o auth_server.o
obj-y := l4-constable.o
