# For the Linux kernel part of Medusa DS9 Security System, L3

# for GCOV coverage profiling
ifdef CONFIG_SECURITY_MEDUSA_GCOV_PROFILE
GCOV_PROFILE := y
endif

O_TARGET := l3.o

obj-y := comm.o registry.o med_cache.o


