tree "fs" clone of file by getfile getfile.filename;
primary tree "fs";
tree "domain" of process;

space all_domains = recursive "domain";
space all_files = recursive "/";

all_domains	ENTER	all_domains,
		READ	all_domains, all_files,
		WRITE	all_domains, all_files,
		SEE	all_domains, all_files;

* getprocess * {
	enter(process, @"domain/init");
	process.med_sact = 0;
	process.audit = 1;
	return ALLOW;
}

* getfile * {
	file.med_oact = 0x3fffffff;
	file.vs = space all_files;
	return ALLOW;
}

* getipc * {
	ipc.med_oact = 0x3fffffff;
	ipc.vs = space all_files;
	return ALLOW;
}

* ipc_perm * { return ALLOW; }
* ipc_msgsnd * { return DENY; }
* ipc_ctl * { return ALLOW; }

function _init
{
	local process init.pid = 1;

	if (fetch init) {
		init.audit = 1;
		update init;
	}
}
