tree "fs" clone of file by getfile getfile.filename;
primary tree "fs";
tree "domain" of process;

space all_domains = recursive "domain";
space all_objects = recursive "/";

all_domains	ENTER	all_domains,
		READ	all_domains, all_objects,
		WRITE	all_domains, all_objects,
		SEE	all_domains, all_objects;

function log
{
	local printk buf.message=$1 + "\n";
	update buf;
}

* getprocess * {
	enter(process, @"domain/init");
	process.med_sact = 0x7fffffff;
	return ALLOW;
}

* getsocket * {
	log("MEDUSA_EVENT getsocket");
	return ALLOW;
}

all_domains socket_create {
	log("MEDUSA_EVENT socket_create");
	if (socket_create.type == 5)
		return DENY;
	return ALLOW;
}

* socket_bind_access * {
	log("MEDUSA_EVENT socket_bind_access");
	if (socket.family == 1 && socket.type == 2)
		return DENY;
	return ALLOW;
}

* socket_connect_access * {
	log("MEDUSA_EVENT socket_connect_access");
	if (socket.type == 2)
		return DENY;
	return ALLOW;
}

* socket_listen_access * {
	log("MEDUSA_EVENT socket_listen_access");
	if (socket_listen_access.backlog == 9)
		return DENY;
	return ALLOW;
}

* socket_accept_access * {
	log("MEDUSA_EVENT socket_accept_access");
	if (socket.family == 10)
		return DENY;
	return ALLOW;
}

* socket_sendmsg_access * {
	log("MEDUSA_EVENT socket_sendmsg_access");
	if (socket_sendmsg_access.size == 5)
		return DENY;
	return ALLOW;
}

* socket_recvmsg_access * {
	log("MEDUSA_EVENT socket_recvmsg_access");
	if (socket_recvmsg_access.size == 5)
		return DENY;
	return ALLOW;
}

function _init
{
}
