name: Cache Medusa repository

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
  # only temporary for development
  pull_request:
    branches: master

jobs:
  cache-repo:
    name: Cache the whole repository
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        run: |
          MASTER_HASH=$(git ls-remote https://github.com/Medusa-Team/linux-medusa master | awk '{print $1}')
          CACHE_KEY=master-$MASTER_HASH
          echo "CACHE_KEY=$CACHE_KEY"
          echo "CACHE_KEY=$CACHE_KEY" >> $GITHUB_ENV
      - uses: actions/cache@v3
        id: master-cache-lookup
        with:
          path: ./**
          key: ${{ env.CACHE_KEY }}
          lookup-only: true
      - uses: actions/checkout@v3
        if: steps.master-cache-lookup.outputs.cache-hit == 'false'
        with:
          fetch-depth: 0
